const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./app.ts"];

const doc = {
  info: {
    version: "1.0.0",
    title: "Rocket Food API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3333",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    rocketfood_auth: {
      type: "jwt",
      authorizationUrl: "localhost:3333/session",
      flow: "implicit",
      scopes: {
        create_product: "create your products",
        write_product: "modify products in your account",
      },
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles);
